---
abstract: 'A stash for SQL queries'
author:
  - 'Sebastian Nowicki <sebnow@gmail.com>'
build_requires:
  DBI: 0
  Test::Exception: 0
  Test::MockModule: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
  version: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Stash
provides:
  SQL::Stash:
    file: lib/SQL/Stash.pm
    version: v0.1.0
requires:
  perl: 0
  version: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: v0.1.0
